### ISSUE TITLE
RangeError: Pool2: maxRequests must be a positive integer, Infinity given.

### ISSUE THREAD

**Issue by gkorland** [myndzi/pool2#21]
I'm getting 

> RangeError: Pool2: maxRequests must be a positive integer, Infinity given.

While the docs says 

> **maxRequests**
> An integer greater than 0 (Infinity is also valid), to specify the maximum number of requests that the pool instance will allow. If the request queue exceeds this number, calls to acquire will fail with the error Pool is full.

**Comment by myndzi** [comment]
Sorry about that! Infinity is the default, you can just leave that option off to work around this until I can fix it.

**Comment by myndzi** [comment]
Just pushed a new version, should be good to go
