### ISSUE TITLE
More connections being open that configured.

### ISSUE THREAD

**Issue by b2rsp** [myndzi/pool2#31]
Hi,

I am using Knex with bookshelf:
`"knex": "^0.12.6",`
`"bookshelf": "^0.10.2"`,
`"mssql": "^3.3.0",`

And i have this configuration 
```
 database: {
    acquireConnectionTimeout: 40000,
    client: 'mssql',
    connection: {
        host: '-----',
        port: 1433,
        database: '----'
    },
    pool: {
      min: 0,
      max: 25,
      idleTimeout: 30000,
      syncInterval: 5000
    }
  }
```
And this is the code i initialize the knex:
```
import config from '~/config';

export const knex = require('knex')(config.database);
export const bookshelf = require('bookshelf')(knex);

bookshelf.plugin('pagination');

export default bookshelf;
```

The issue is i have a listener/loop to read AWS SQS and there some times i have spike in terms of connections to the MSSQL beyond the `max` configured (25). I get something 55-70.

And i was wondering if any guys know any idea of what is happening ?

**Comment by myndzi** [comment]
At a glance, might be related to https://github.com/myndzi/pool2/issues/30, which I've scummily left idle since the reporter solved the problem another way. I'll try to have a deeper look within a few days, by which point I should have a branch or a new version you can test and see if you still have this problem with.

**Comment by b2rsp** [comment]
@myndzi Thanks very much for the quick response. I already discovered the issue and there some misunderstanding by reading the TCP connections with the *TIME_WAIT*, so there weren't any *issue* with the *pool* after all. Still thanks very much for the response and good work :)

**Comment by krisreeves-stripe** [comment]
Ah, glad to hear it! Thanks for following up
